apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: beatbuddy
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatbuddy-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: beatbuddy
            - name: MYSQL_USER
              value: beyond
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beatbuddy-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi